# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Diego A. Tejada-Arango <diego.tejadaarango@tno.nl>,Germ치n Morales-Espa침a
    <german.morales@tno.nl>,Lauren Clisby <lauren.clisby@tno.nl>,Ni Wang <ni.wang@tno.nl>,Abel
    Soares Siqueira <abel.s.siqueira@gmail.com>,Suvayu Ali <s.ali@esciencecenter.nl>,Laurent
    Soucasse <l.soucasse@esciencecenter.nl>,Greg Neustroev <G.Neustroev@tudelft.nl>
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: Apache-2.0
LicenseCopyrightHolders: Diego A. Tejada-Arango, Germ치n Morales-Espa침a, Lauren Clisby,
    Ni Wang, Abel Soares Siqueira, Suvayu Ali, Laurent Soucasse, Greg Neustroev
PackageName: TulipaEnergyModel
PackageOwner: TulipaEnergy
PackageUUID: 5d7bd171-d18e-45a5-9111-f1f11ac5d04d
_commit: v0.12.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
