name = "TulipaEnergyModel"
uuid = "5d7bd171-d18e-45a5-9111-f1f11ac5d04d"
authors = ["Diego A. Tejada-Arango <diego.tejadaarango@tno.nl>", "Germán Morales-España <german.morales@tno.nl>", "Lauren Clisby <lauren.clisby@tno.nl>", "Ni Wang <ni.wang@tno.nl>", "Abel Soares Siqueira <abel.s.siqueira@gmail.com>", "Suvayu Ali <s.ali@esciencecenter.nl>", "Laurent Soucasse <l.soucasse@esciencecenter.nl>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
CSV = "0.10"
DataFrames = "1"
Graphs = "1.8"
HiGHS = "1"
JuMP = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
