# This file was created because of issue #133 (run tests faster on PRs)
# If you want to run the full test, change Test.yml and delete this file
name: Test on PR
on:
    pull_request:
        paths:
            - "src/**"
            - "test/**"
            - "*.toml"
concurrency:
    # Skip intermediate builds: always.
    # Cancel intermediate builds: only if it is a pull request build.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
    contents: read
jobs:
    test:
        name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                version:
                    - "1.6"
                    - "1"
                os:
                    - ubuntu-latest
                arch:
                    - x64
        steps:
            - uses: actions/checkout@v3
            - uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.version }}
                  arch: ${{ matrix.arch }}
            - uses: julia-actions/cache@v1
            - uses: julia-actions/julia-buildpkg@v1
            - uses: julia-actions/julia-runtest@v1
            - uses: julia-actions/julia-processcoverage@v1
              if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
            - uses: codecov/codecov-action@v4
              if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
              with:
                  files: lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }} # Defined in the organization secrets
